#pragma once

#include <windows.h>
#include <cstdint>

enum class Color : uint8_t {
    Black,
    DarkBlue,
    DarkGreen,
    DarkCyan,
    DarkRed,
    DarkMagenta,
    DarkYellow,
    Grey,
    DarkGrey,
    Blue,
    Green,
    Cyan,
    Red,
    Magenta,
    Yellow,
    White,
};

inline WORD toFg(Color c) {
    return (WORD)c;
}

inline WORD toBg(Color c) {
    return toFg(c) << 4;
}

namespace FG {
enum {
    BLACK = 0,
    DARK_BLUE = FOREGROUND_BLUE,
    DARK_GREEN = FOREGROUND_GREEN,
    DARK_CYAN = FOREGROUND_BLUE | FOREGROUND_GREEN,
    DARK_RED = FOREGROUND_RED,
    DARK_MAGENTA = FOREGROUND_RED | FOREGROUND_BLUE,
    DARK_YELLOW = FOREGROUND_RED | FOREGROUND_GREEN,
    GREY = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
    DARK_GREY = FOREGROUND_INTENSITY,
    BLUE = FOREGROUND_INTENSITY | FOREGROUND_BLUE,
    GREEN = FOREGROUND_INTENSITY | FOREGROUND_GREEN,
    CYAN = FOREGROUND_INTENSITY | FOREGROUND_BLUE | FOREGROUND_GREEN,
    RED = FOREGROUND_INTENSITY | FOREGROUND_RED,
    MAGENTA = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE,
    YELLOW = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN,
    WHITE = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
};
}

namespace BG {
enum {
    BLACK = 0,
    DARK_BLUE = BACKGROUND_BLUE,
    DARK_GREEN = BACKGROUND_GREEN,
    DARK_CYAN = BACKGROUND_BLUE | BACKGROUND_GREEN,
    DARK_RED = BACKGROUND_RED,
    DARK_MAGENTA = BACKGROUND_RED | BACKGROUND_BLUE,
    DARK_YELLOW = BACKGROUND_RED | BACKGROUND_GREEN,
    GREY = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
    DARK_GREY = BACKGROUND_INTENSITY,
    BLUE = BACKGROUND_INTENSITY | BACKGROUND_BLUE,
    GREEN = BACKGROUND_INTENSITY | BACKGROUND_GREEN,
    CYAN = BACKGROUND_INTENSITY | BACKGROUND_BLUE | BACKGROUND_GREEN,
    RED = BACKGROUND_INTENSITY | BACKGROUND_RED,
    MAGENTA = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_BLUE,
    YELLOW = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN,
    WHITE = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
};
}
